# Generated by Django 3.1.7 on 2021-03-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fake',
            field=models.CharField(choices=[('F', 'Fake'), ('T', 'Truth')], default='F', max_length=1),
        ),
    ]
